/***************************************************************************************************
*  COPYRIGHT DaTang Mobile Communications Equipment CO.,LTD   *
*****************************************************************************************************
* Filename        : os_timer.c                                                                       
*
* Description     : This file is to do some op about os timer interrupt 
*                                                                                                
*
* Notes           : NA                                       
*
*--------------------------------------------------------------------------------------------------------
* Change History: 
*--------------------------------------------------------------------------------------------------------
*          
*  0.01              2004-12-15       wangjinrong
*		     2004-12-27	      wangjinrong      add code for timer B,C handler
*                    2004-12-28       wangjinrong      change ,use a macro OS_TIMER_INTERRPU_FREQ to define
*                                                       timer frequency
*                    2005-01-25       wangjinrong      change code ,handle timer A,B,C currently;
*  0.02     JS_Enh00000108 : weiwu       : 2005-05-15 : adjust Frequest number 
***********************************************************************************************************/


#include "os_low_level_type.h"

/*unsigned int sp_fiq=0;
unsigned int sp_sys=0;
*/

#define TIMER_BASEADD       0x80240000

#define TIMER_STATUS	      (*((volatile u16 *)(TIMER_BASEADD+0x00)))
#define TIMER_A_CONTROL	    (*((volatile u16 *)(TIMER_BASEADD+0x02)))
#define TIMER_A_ENDCOUNTL	  (*((volatile u16 *)(TIMER_BASEADD+0x08)))
#define TIMER_A_ENDCOUNTH	  (*((volatile u16 *)(TIMER_BASEADD+0x0a)))

//#define ARNHWMASK1 				(*(volatile u16 *)0x80000202)

extern void _tx_timer_interrupt(void);
void timer_handler();

/*******************************************************************************
* Function	: timer_init												   	   
* Description	: timer initialize in here ,config control register and count register of timerA,
*		                                               
* Relation	: timer frequency is 128 HZ, timer generated by timerA in monaco board
*		  timerA clock is 32K
*		  
* Params	: 						     									
* 																			   
*   Name		Type		In/Out 		Description							   
* -------- 		---- 		------   	----------- 				       
*  none			none		none		none
*					 														   
* Return	: none
*
* Notes		: timer frequency is 128 HZ fixed
*  		                                    			   
*******************************************************************************/
void timer_init(void)
{
    TIMER_A_CONTROL = 0x024;
    /* FIX Enh00000020 BEGIN DATE:2005-03-23 AUTHOR NAME fangjiayuan */
    /* FIX Enh00000108 BEGIN DATE:2005-05-15 AUTHOR NAME weiwu */
    TIMER_A_ENDCOUNTL =( 0x7d00 >> OS_TIMER_INTERRPU_FREQ);		//clock frequency = 1s/64
    /* FIX Enh00000108 END DATE:2005-05-15 AUTHOR NAME weiwu */
    /* FIX Enh00000020 END DATE:2005-03-23 AUTHOR NAME fangjiayuan */
    TIMER_A_CONTROL = 0x0171;			//autorepeat--0x171 oneshop---0x131
    
    tp_os_register_vector(GROUP1,PRIO12,(unsigned int)timer_handler);
    
    tp_os_unmask_irq(GROUP1,PRIO12);
}

/*******************************************************************************
* Function	: timer_handler												   	   
* Description	: timer interrupt handler, do all of timer function of OS, such as 
*		  tick count, time slice schedule , timer.                                              
* Relation	: timer frequency is 128 HZ, timer generated by timerA in monaco board
*		  timerA clock is 32K
*		  
* Params	: 						     									
* 																			   
*   Name		Type		In/Out 		Description							   
* -------- 		---- 		------   	----------- 				       
*  none			none		none		none
*					 														   
* Return	: none
*
* Notes		: none
*  		                                    			   
*******************************************************************************/


typedef void (*intr_function)(void);
#define NULL_FUNC (unsigned int)0

unsigned int  timer_handler_func_tbl[2]={NULL_FUNC,NULL_FUNC};

void timer_handler()
{
    unsigned short irqstat;
    static int count=0;
    //*(unsigned short *)0x0c000008 = 0xffff; 
    //*(unsigned short *)0x0c000010 = count++; 
    //*(unsigned short *)0x80180000 = 0x1;*/
    //SerialOutputString("\nit in C_timer_handle "); 
        	
    irqstat=*(volatile unsigned short *)0x80240000;
    if( irqstat & 0x3 )
    	_tx_timer_interrupt();
    //else if( ( irqstat & 0xc ) && timer_handler_func_tbl[0] )
    if( ( irqstat & 0xc ) && timer_handler_func_tbl[0] )
    	((intr_function)timer_handler_func_tbl[0])();
    //else if( (irqstat & 0x30) && timer_handler_func_tbl[1] )
    if( (irqstat & 0x30) && timer_handler_func_tbl[1] )
    	((intr_function)timer_handler_func_tbl[1])();
    //SerialOutputString("\nSP_FIQ =  "); 
    //SerialOutputHex(sp_fiq); 
    //clr status
    *(volatile unsigned short *)0x80240000 = irqstat;
}

/*
#define TIMER_B 1
#define TIMER_C 2
int tp_os_timer_register(int who,unsigned int func)
{
	if(who==TIMER_B) timer_handler_func_tbl[0]=func;
	else if(who=TIMER_C) timer_handler_func_tbl[1]=func;
	else return 1;
	return 0;
}
*/